README.md
I've added to the ReadMe.md a list of coding standards that our code should follow. If you have any comments or additions feel free to discuss.
=> Feature coding standards

EducationalSolarSimulatorDEV/Assets/Prefabs/Empty Body.prefab
Updated camera references in the empty body prefab. should work now.
=> Body Prefab Camera Reference Fix

OrbitLearn/Assets/Prefabs/UI/BodyInfoPrompt.prefab, OrbitLearn/Assets/Prefabs/UI/BodyInfoPrompt.prefab.meta, OrbitLearn/Assets/Prefabs/UI/PanelSlider.prefab, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/BodyPromptScript.cs, OrbitLearn/Assets/Scripts/BodyPromptScript.cs.meta, OrbitLearn/Assets/Scripts/GameManager.cs, OrbitLearn/Assets/Scripts/UISliderMenu.cs
Added and implemented the body info prompt
=> Feature body info prompt

OrbitLearn/Assets/Prefabs/UI/Body Information Panel.prefab, OrbitLearn/Assets/Prefabs/UI/Body_List_Panel.prefab, OrbitLearn/Assets/Prefabs/UI/PanelSlider.prefab, OrbitLearn/Assets/Scenes/HomeScene.unity, OrbitLearn/Assets/Scripts/BodyPromptScript.cs
=> Feature ultra cosmetics

OrbitLearn/Assets/Scripts/Body.cs, OrbitLearn/Assets/Scripts/GameManager.cs
=> gravity implementation

OrbitLearn/Assets/Scripts/NBody.cs
=> increased gravity

OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/BodyPromptScript.cs, OrbitLearn/Assets/Scripts/GameManager.cs, OrbitLearn/Assets/Scripts/UISliderMenu.cs
Still have issue with the click prompt on the body, which will need to fix in a future release.
=> Fixed UI somewhat and Radius of Bodies

OrbitLearn/Assets/Prefabs/UI/BodyInfoPrompt.prefab, OrbitLearn/Assets/Scripts/BodyPromptScript.cs
I've added support for mass to use scientific notation, and a short explanation of scientific notation on the body creation menu
=> Added support for scientific notation and a brief explanation for it

OrbitLearn/Assets/Scripts/BodiesInfoButton.cs, OrbitLearn/Assets/Scripts/GameManager.cs, OrbitLearn/Assets/Scripts/UISliderMenu.cs
Growing the text block for the bodies panel dependent on bodies present
=> Feature dynamic button scroll bar addition

OrbitLearn/Assets/Prefabs/UniverseCenter.prefab, OrbitLearn/Assets/Scripts/MoveCameraOnTouch.cs, OrbitLearn/Assets/Scripts/MoveCameraOnTouch.cs.meta
yeah yeah look pally I understand the thing is in uppercase I don't have aiuefiodjhainjoekpofivnoeajlkwQ MEWVJ ZNJAKPL;DJLKAF
=> Added a camera update and potentially a functional mobile camera

OrbitLearn/Assets/Prefabs/UI/BodyInfoPrompt.prefab, OrbitLearn/Assets/Scripts/BodyPromptScript.cs, OrbitLearn/ProjectSettings/EditorBuildSettings.asset
Note we still have some input error bugs going on but for now, this is fine (for future use check the bodypromptscript to fix these issues)
=> Feature UI input fix

OrbitLearn/Assets/Prefabs/UI/Body_List_Panel.prefab, OrbitLearn/Assets/Prefabs/UI/ButtonCosmetic.prefab, OrbitLearn/Assets/Prefabs/UI/ButtonSample.prefab, OrbitLearn/Assets/Prefabs/UI/ButtonSample.prefab.meta, OrbitLearn/Assets/Prefabs/UI/PanelSlider.prefab, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/BodiesInfoButton.cs, OrbitLearn/Assets/Scripts/GameManager.cs, OrbitLearn/Assets/Scripts/TextButton.cs, OrbitLearn/Assets/Scripts/TextButton.cs.meta
Buttons on the Bodies Panel. They have a debug making it known they were clicked. To be implemented.
=> Feature bodies buttons display

OrbitLearn/Assets/Prefabs/UI/ButtonCosmetic.prefab, OrbitLearn/Assets/Scripts/BodiesInfoButton.cs, OrbitLearn/Assets/Scripts/GameManager.cs
=> Body Information Panel buttons can now focus on individual planets.

OrbitLearn/Assets/Prefabs/Empty Body.prefab, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/MaterialAssign.cs, OrbitLearn/ProjectSettings/TagManager.asset
=> Feature visability

OrbitLearn/Assets/Scenes/PresetSimScene.unity, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/BodyIcon.cs, OrbitLearn/Assets/Scripts/GameManager.cs, OrbitLearn/Assets/Scripts/UIPresetSimulations.cs, OrbitLearn/Assets/Scripts/UISliderMenu.cs
- Added functional Preset simulation selection menu to preset scene
- added new presets.
- removed modification of body colliders when certain distance from camera
=> Added functional Preset Simulation Selection menu to PresetSimulation scene

OrbitLearn/Assets/Scripts/UIPresetSimulations.cs
Math.pow added to all preset sim mass sizes.
=> Feature preset math pow

OrbitLearn/Assets/Scenes/EquationScene.unity, OrbitLearn/Assets/Scenes/InfoScene.unity
updated the equation and info sheet to make it neater. Also standardized all the colors of the home buttons
=> Feature sheets cleanup

OrbitLearn/Assets/Scripts/BodiesInfoButton.cs, OrbitLearn/Assets/Scripts/BodyPromptScript.cs
This method checks input for the name, and if there is a null input will name the body 'Body#' where the number is determined by the current body count from the game manager.
=> Input Name Default Requirement 

OrbitLearn/Assets/Prefabs/UI/Body Information Panel.prefab, OrbitLearn/Assets/Scenes/PresetSimScene.unity, OrbitLearn/Assets/Scenes/SimulationScene.unity
=> Feature new hamburger blt edition

OrbitLearn/Assets/Prefabs/Empty Body.prefab, OrbitLearn/Assets/Prefabs/UI/BodyInfoPrompt.prefab, OrbitLearn/Assets/Scenes/PresetSimScene.unity, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/Body.cs, OrbitLearn/Assets/Scripts/BodyPromptScript.cs, OrbitLearn/Assets/Scripts/GameManager.cs, OrbitLearn/Assets/Scripts/UIPresetSimulations.cs
This works by having spotlights around the body to make the appearance of it glowing. As a result, there are two notable things that can happen, though not necessarily need fixing. The first is that depending on the body size the glow will be bright/darker due to the light coverage of the spotlight, a solution if needed it could be to make the intensity a factor of the size. The second is that if a non glowing body comes into contact with a glowing one both will appear to glow due to how this lighting operates.
=> Feature Glow

OrbitLearn/Assets/Scripts/GameManager.cs
Max body count reduced from 50 to 25
=> Max body count reduced from 50 to 25

OrbitLearn/Assets/Scenes/PresetSimScene.unity, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/GameManager.cs, OrbitLearn/Assets/Scripts/UISliderMenu.cs
Pause play changes text. Same as previous PR, but last one was scrapped due to weird merge conflict. This one is clean to merge without killing the panel slider.
=> Pause/Play redone, since merge conflicts killed it the first time.

OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/UISliderMenu.cs
=> Feature body info pane reallignment

OrbitLearn/Assets/Prefabs/UI/Preset Simulations Panel.prefab, OrbitLearn/Assets/Scripts/UIPresetSimulations.cs
Add new templates into the new template screen
=> Create new templates, and rename buttons to match them

OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/BodiesInfoButton.cs
The source of the problems was a single anchor point on the text container was changed from stretch to middle. Button allignments were raised to my personal preference
=> Fixing bodies panel allignment after the Body info pane last saturday.

OrbitLearn/Assets/Prefabs/UniverseCenter.prefab, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/BodiesInfoButton.cs, OrbitLearn/Assets/Scripts/GameManager.cs, OrbitLearn/Assets/Scripts/MoveCameraOnTouch.cs, OrbitLearn/Assets/Scripts/UIPresetSimulations.cs
- Overhauled selection/deslection of planets
- Smoothed out (hopefully) camera movement on mobile
=> Feature cool camera stuff

OrbitLearn/Assets/Prefabs/Empty Body.prefab, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/Body.cs, OrbitLearn/Assets/Scripts/BodyPromptScript.cs, OrbitLearn/Assets/Scripts/GameManager.cs
This should now properly implement glowing of bodies when spawned and edited along with having proper radiance while glowing.
=> Feature glow lights

OrbitLearn/Assets/Prefabs/UI/Preset Simulations Panel.prefab, OrbitLearn/Assets/Scenes/SimulationScene.unity
Cosmetic improvement to preset panel
=> Cosmetically Improved preset panel

OrbitLearn/Assets/Prefabs/UI/Preset Simulations Panel.prefab, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/BodyPromptScript.cs
Glow toggle is now off by default and remembers the glow state of the body.
=> Glow Toggle States

OrbitLearn/Assets/Prefabs/UI/PanelSlider.prefab, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/GameManager.cs, OrbitLearn/Assets/Scripts/RotationDisplay.cs, OrbitLearn/Assets/Scripts/UIRefHandler.cs, OrbitLearn/Assets/Scripts/UISliderMenu.cs
Button to toggle the rotation display being active on panel slider.
=> Feature bugs and rot disp set active

OrbitLearn/Assets/Scripts/BodyPromptScript.cs, OrbitLearn/Assets/Scripts/GameManager.cs, OrbitLearn/Assets/Scripts/UIAddBodyPanel.cs, OrbitLearn/Assets/Scripts/UIPresetSimulations.cs
Now Constrains are put on mass and speed for spawning a body via user input and the tryspawn method within the gamemanager,
1) 1e9 >= Mass <= 1e-7
2) 200 >= Speed <= -200
=> Feature Mass & Speed Body Limit

OrbitLearn/Assets/Scripts/GameManager.cs
Set body position spawn limits based on the center of the universe or the centroid with a +-50 range
=> Spawn Body Limits

OrbitLearn/Assets/Prefabs/Empty Body.prefab, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/BodyIcon.cs, OrbitLearn/Assets/Scripts/GameManager.cs
Hell yeah, Logan did the thing everybody said was impossible once again
Bodies are now interactable from long distances when messing with them. The specifics of the collider exploder may need a smidgen of fine tuning in the future, but from what I saw they work just fine.
=> Long-Range Body Touching

OrbitLearn/Assets/Scenes/SimulationScene.unity
In the future, this is something that can be easily changed by modifying the values of MoveCamOnTouch in the UniverseCenter
=> Lowered Sensitivity of the Camera on mobile

OrbitLearn/Assets/Prefabs/UI/PanelSlider.prefab, OrbitLearn/Assets/Prefabs/UI/Preset Simulations Panel.prefab, OrbitLearn/Assets/Scenes/SimulationScene.unity, OrbitLearn/Assets/Scripts/UIPresetSimulations.cs
Import/ Export keep same exact functionality, but are now with the template people
=> Feature load into template and save states

OrbitLearn/Assets/Scripts/Body.cs, OrbitLearn/Assets/Scripts/GameManager.cs
Does not filter out jupiters, will do that momentarily
=> Feature unique rotation

OrbitLearn/Assets/Scripts/GameManager.cs
=> PR of shame
